//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Producto_Factura = new HashSet<Producto_Factura>();
        }
    
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public int IdCliente { get; set; }
        public string Telefono { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Producto_Factura> Producto_Factura { get; set; }
    }
}
