//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Producto_Factura = new HashSet<Producto_Factura>();
        }
        public int PaginaActual { get; set; }
        public int TotalItems { get; set; }
        public int RegistroPorPagina { get; set; }

        public decimal SubTotal { get; set; }
        public decimal Total { get; set; }
        public decimal IVA { get; set; }
        public int IdFactura { get; set; }
        public int IdCondicion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IDCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual CondicionFactura CondicionFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_Factura> Producto_Factura { get; set; }
    }
}
