//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Producto_Factura = new HashSet<Producto_Factura>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Precio { get; set; }
        public string Nombre { get; set; }
        public bool Estado { get; set; }
        public int Cantidad { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual ICollection<Producto_Factura> Producto_Factura { get; set; }
    }
}
